name: Pack NuGet

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string

jobs:
  pack:
    runs-on: ubuntu-latest
    outputs:
      package_path: ${{ steps.pack.outputs.package_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
        - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.1.x'

      - name: Pack project
        id: pack
        run: |
          dotnet pack ${{ inputs.project_path }} -c Release --no-restore --output pack
          PACKAGE_NAME=$(basename ${{ inputs.project_path }} .csproj)
          PACKAGE_PATH="pack/${PACKAGE_NAME}.${{ github.ref_name }}.nupkg"
          echo "package_path=$PACKAGE_PATH" >> $GITHUB_ENV
        env:
          PACKAGE_VERSION: ${{ github.ref_name }}
      
      - name: Upload pack artifacts
        uses: actions/upload-artifact@v4
          with: 
            name: pack/*.nupkg
            path: pack
            retention-days: 5