name: Push to NuGet

description: 'A GitHub Action to push a NuGet package to a NuGet repository.'

inputs:
  package_path:
    required: true
    description: 'Path to the NuGet package to push.'
    type: string

secrets:
  NUGET_API_KEY:
    required: true
  NUGET_SOURCE:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '2.1.x'

    - name: Download Package
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages
        path: ./pack  # Ensure the path is correct

    - name: Push package to NuGet
      run: |
        dotnet nuget push "${{ inputs.package_path }}" --api-key "${{ secrets.NUGET_API_KEY }}" --source "${{ secrets.NUGET_SOURCE }}"
      shell: bash  # Specify the shell to use
